server:
  port: 80
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      resolve-lazily: true

#hadoop:
#  hdfs:
#    url: hdfs://192.168.64.130:9000

hadoop:
  hdfs:
    url: hdfs://hadoop101:9000
